export default {
  'a': ['a', 'amazon', 'cb3', 'pay2', 'y1', 'y3', '5social', 'arroba', 'arch'],
  'b': ['b', 'bill1'],
  'c': ['c', 'cabify', 'cb1', '3social', 'cocoapods', 'checkpoint'],
  'd': ['d', 'd2'],
  'e': ['pay5', 'cb6', '4money', 'y5', 'emacs'],
  'f': ['facebook', 'f'],
  'g': ['cb5', 'grammarnazi'],
  'h': ['cb2', 'h'],
  'i': ['bill2', '4social', 'information_source'],
  'j': ['juventus', 'j'],
  'k': ['k', 'k2'],
  'l': ['bill3', 'bill4', 'y6', '6social'],
  'm': ['1money', 'pay4', 'y2', 'm', 'mc'],
  'n': ['neovim', 'pay6', '3money'],
  'o': ['o', '2money', 'o2', 'y7', 'orkut', '2social'],
  'p': ['pay1', 'pinterest', 'parking'],
  'q': ['q', 'q2'],
  'r': ['cb4', 'cb7', 'y4', 'registered'],
  's': ['pay8', 'bill5', '1social'],
  't': ['pay7', 't'],
  'u': ['u-300', 'u'],
  'v': ['v2', 'v3'],
  'w': ['w', 'vw'],
  'x': ['x', 'heavy_multiplication_x', 'negative_squared_cross_mark'],
  'y': ['5money', 'pay3'],
  'z': ['z', 'z2'],
  '0': ['zero'],
  '1': ['one'],
  '2': ['two'],
  '3': ['three'],
  '4': ['four'],
  '5': ['five'],
  '6': ['six'],
  '7': ['seven'],
  '8': ['eight'],
  '9': ['nine'],
  '!': ['exclamation', 'grey_exclamation'],
  '?': ['marioquestion', 'question', 'grey_question'],
  '.': ['dot'],
  ',': ['comma'],
  ' ': ['space', 'space2', 'space3', 'space4'],
};
